application: conference-org-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /_ah/spi/.*
  script: conference.api
  secure: always

- url: /crons/set_announcement
  script: main.app
  login: admin

- url: /tasks/send_confirmation_email
  script: main.app
  login: admin

- url: /tasks/send_confirmation_session_email
  script: main.app
  login: admin

- url: /tasks/set_featured_speaker
  script: main.app
  login: admin  

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
